//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVat.Domain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorsInInvoices
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Postal { get; set; }
        public string BuildingNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public long NIP { get; set; }
        public Nullable<int> Regon { get; set; }
        public int ContractorId { get; set; }
    
        public virtual Contractors Contractors { get; set; }
        public virtual Invoices Invoices { get; set; }
    }
}
