<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="Default.aspx.cs" Inherits="vatplan.asp.Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Produkty</h2>
    <asp:HyperLink NavigateUrl="~/AddProduct.aspx" Text="Nowy produktd" runat="server" />
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:GridView runat="server" ID="productsGrid"
        ItemType="PlanVat.Domain.DB.Products" DataKeyNames="Id"
        SelectMethod="productsGrid_GetData"
        DeleteMethod="productsGrid_DeleteItem"
        UpdateMethod="productsGrid_UpdateItem"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateColumns="False" AlternatingRowStyle-VerticalAlign="Middle">

        <Columns>
            <asp:DynamicField DataField="Name" HeaderText="Nazwa" />
            <asp:DynamicField DataField="Description" HeaderText="Opis" />
            <asp:DynamicField DataField="PKWiU" HeaderText="PKWiU" />

            <asp:TemplateField HeaderText="J.m.">
                <ItemTemplate>
                    <asp:Label Text="<%# Item.UnitsOfMeasure.Name %>" runat="server" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Stawka Vat">
                <ItemTemplate>
                    <asp:Label Text="<%# Item.VatRates.Name %>" runat="server" />
                </ItemTemplate>
            </asp:TemplateField>

        </Columns>

    </asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:VatplanConnectionString %>" 
    DeleteCommand="DELETE FROM [Products] WHERE [Id] = @Id" 
    InsertCommand="INSERT INTO [Products] ([Name], [Description], [PKWiU], [Price], [VatRateId]) VALUES (@Name, @Description, @PKWiU, @Price, @VatRateId)" 
    SelectCommand="SELECT [Name], [Id], [Description], [PKWiU], [Price], [VatRateId] FROM [Products]" 
    UpdateCommand="UPDATE [Products] SET [Name] = @Name, [Description] = @Description, [PKWiU] = @PKWiU, [Price] = @Price, [VatRateId] = @VatRateId WHERE [Id] = @Id">
    <DeleteParameters>
        <asp:Parameter Name="Id" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="Name" Type="String" />
        <asp:Parameter Name="Description" Type="String" />
        <asp:Parameter Name="PKWiU" Type="String" />
        <asp:Parameter Name="Price" Type="Decimal" />
        <asp:Parameter Name="VatRateId" Type="Int32" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="Name" Type="String" />
        <asp:Parameter Name="Description" Type="String" />
        <asp:Parameter Name="PKWiU" Type="String" />
        <asp:Parameter Name="Price" Type="Decimal" />
        <asp:Parameter Name="VatRateId" Type="Int32" />
        <asp:Parameter Name="Id" Type="Int32" />
    </UpdateParameters>
</asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" OnRowDataBound="GridView1_RowDataBound">
        <Columns>
            <asp:TemplateField HeaderText="Name" SortExpression="Name">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:TextBox ID="NameTextBox" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Description" SortExpression="Description">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Description") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:TextBox ID="DescriptionTextBox" runat="server" Text='<%# Bind("Description") %>'></asp:TextBox>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PKWiU" SortExpression="PKWiU">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("PKWiU") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:TextBox ID="PkwiuTextBox" runat="server" Text='<%# Bind("PKWiU") %>'></asp:TextBox>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Price" SortExpression="Price">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Price") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="VatRateId" HeaderText="VatRateId" SortExpression="VatRateId" />
        </Columns>
    </asp:GridView>
    <asp:Button ID="UpdateButton" runat="server" OnClick="UpdateButton_Click" Text="Update" />
</asp:Content>
